fixtures:
  repositories:
    concat:           'git://github.com/puppetlabs/puppetlabs-concat'
    stdlib:           'git://github.com/puppetlabs/puppetlabs-stdlib'
    apt:              'git://github.com/puppetlabs/puppetlabs-apt'
    yumrepo_core:     'git://github.com/puppetlabs/puppetlabs-yumrepo_core'

  symlinks:
    ansible: "#{source_dir}"
