---
sudo: false
language: ruby
dist: trusty
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - bundle exec rake $CHECK
  - bundle exec rake metadata_lint
  - bundle exec rake syntax
  - bundle exec rake spec
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.4.0
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 5.0"
  - rvm: 2.4.1
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 5.1.0"
  - rvm: 2.1.9
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.0"
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: othersskins@gmail.com